all:
  hosts:
    host1:
      ansible_host: SERVER_SSH_IP
      ansible_port: SERVER_SSH_PORT
      ansible_ssh_private_key_file: SERVER_SSH_PRIVATE_KEY_PATH

  children:
    sopds:
      hosts:
        host1:
