---

postgres_service: postgres
postgres_image: postgres:11
postgres_volume: postgres
postgres_volume_type: volume
postgres_network: postgres
postgres_db: postgres
postgres_user: postgres
postgres_password: postgres
